"""Build and query a source-agnostic author corpus."""

from author_corpus.answer_review import (
    AnswerClaimReview,
    AnswerReviewAction,
    AnswerReviewRecord,
    AnswerReviewStore,
    ReviewedTrainingExample,
    TrainingEvidence,
    export_reviewed_training_examples,
    review_trace_answer,
)
from author_corpus.answering import GroundedAnswer, GroundedAnswerer
from author_corpus.audit import (
    EVIDENCE_SPAN_VERSION,
    AuditedClaim,
    ClaimRelation,
    EvidenceLedger,
    EvidenceSpan,
    EvidenceValidationIssue,
    validate_evidence_spans,
)
from author_corpus.catalog import AuthorDocumentStats, CorpusCatalog
from author_corpus.claim_classification import (
    CLAIM_EVIDENCE_LABELS,
    ClaimClassificationCase,
    ClaimClassificationCaseResult,
    ClaimClassificationEvaluation,
    ClaimClassifier,
    ClaimEvidenceDecision,
    ClaimEvidenceLabel,
    ClaimEvidenceSignals,
    ClaimLabelMetrics,
    EvidenceVoice,
    classify_claim_evidence,
    evaluate_claim_classifier,
    load_claim_classification_cases,
    validate_claim_classification_sources,
)
from author_corpus.claim_extraction import (
    AnswerClaimCandidate,
    AnswerClaimExtraction,
    ClaimEvidenceAssessment,
    extract_answer_claims,
    extract_grounded_answer_claims,
)
from author_corpus.conversation import (
    ConversationMessage,
    ConversationResolution,
    ConversationRole,
    ConversationTurn,
    ask_conversational,
    resolve_conversation_query,
)
from author_corpus.evaluation import (
    RelevantPassage,
    RetrievalBenchmark,
    RetrievalCase,
    RetrievalCaseResult,
    RetrievalEvaluation,
    RetrievalStrategyEvaluation,
    evaluate_retrieval,
    evaluate_retrieval_strategies,
    load_retrieval_cases,
)
from author_corpus.exact import (
    CatalogAuthorCount,
    CatalogAuthorshipResult,
    CatalogCoauthorCount,
    CatalogCoverage,
    CatalogDocumentResult,
    ExactCatalogArguments,
    ExactCatalogResult,
    ExactCatalogStatus,
    execute_catalog_query,
)
from author_corpus.hybrid import (
    ReciprocalRankFusionRetriever,
    RetrievalProfiles,
    RetrieverArm,
    bm25_index_exists,
    build_retrieval_profiles,
    load_or_build_bm25_retriever,
)
from author_corpus.identity import (
    AuthorIdentity,
    AuthorQueryResolution,
    parse_author_aliases,
    resolve_author_query,
)
from author_corpus.indexing import INDEX_PIPELINE_VERSION
from author_corpus.ingestion import load_corpus, load_corpus_config
from author_corpus.models import (
    CorpusDocument,
    CorpusLoadResult,
    LoadIssue,
    SourceReference,
)
from author_corpus.persistence import CacheLayout, corpus_fingerprint
from author_corpus.querying import build_catalog_tools
from author_corpus.reasoning import (
    BoundedReasoningEngine,
    ClaimVerifier,
    ConservativeClaimVerifier,
    plan_reasoning,
    requires_multistep_reasoning,
)
from author_corpus.reasoning_models import (
    ClaimVerification,
    ReasonedAnswer,
    ReasoningPlan,
    ReasoningRound,
    ReasoningStep,
    ReasoningTrace,
)
from author_corpus.retrieval import (
    RetrievalContribution,
    RetrievedPassage,
    SemanticCorpusSearch,
    SemanticSearchResult,
)
from author_corpus.review import (
    ClaimReviewAction,
    ClaimReviewProposal,
    ClaimReviewRecord,
    ClaimReviewStore,
    ClaimReviewWorkspace,
    ResolvedClaimStatus,
    apply_claim_review,
    review_claim_proposal,
)
from author_corpus.routing import (
    CatalogTool,
    QueryRoute,
    QueryRouteDecision,
    RouteMetrics,
    RoutingCase,
    RoutingCaseResult,
    RoutingEvaluation,
    evaluate_query_router,
    load_routing_cases,
    route_query,
)
from author_corpus.runtime import QueryRuntime, RuntimeSettings, load_query_runtime
from author_corpus.scope import AuthorScope
from author_corpus.service import CorpusQueryResult, CorpusQueryService, QueryTiming, QueryTraceContext
from author_corpus.summaries import (
    CachedChunkSummary,
    CachedCorpusSynthesis,
    CachedSummary,
    DocumentSummaryBuildResult,
    KnowledgeBuildResult,
    SummaryProgress,
    SummaryStore,
    build_cached_document_summaries,
    build_cached_knowledge,
)
from author_corpus.synthesis import (
    EVIDENCE_SYNTHESIS_VERSION,
    EvidenceBoundSynthesis,
    EvidenceSynthesisStore,
    SynthesisClaimGroup,
    SynthesisCoverage,
    build_evidence_bound_synthesis,
)
from author_corpus.timing import TimingLog, TimingRecord
from author_corpus.trace_evaluation import (
    GeneratedClaimCaseResult,
    GeneratedClaimEvaluation,
    GeneratedClaimEvaluationCase,
    GeneratedClaimLabelMetrics,
    evaluate_generated_claims,
    load_generated_claim_cases,
)
from author_corpus.tracing import (
    GenerationTraceSettings,
    QueryTrace,
    QueryTraceStore,
    RetrievalTraceSettings,
    TracedEvidence,
    TraceFreshness,
)
from author_corpus.voice import VoiceAnalysis, VoiceSpan, analyze_voice
from author_corpus.workflow import NotebookRunOptions

__all__ = [
    "AuditedClaim",
    "AnswerClaimReview",
    "AnswerClaimCandidate",
    "AnswerClaimExtraction",
    "AnswerReviewAction",
    "AnswerReviewRecord",
    "AnswerReviewStore",
    "AuthorDocumentStats",
    "AuthorIdentity",
    "AuthorQueryResolution",
    "AuthorScope",
    "BoundedReasoningEngine",
    "CacheLayout",
    "CatalogAuthorCount",
    "CatalogAuthorshipResult",
    "CatalogCoauthorCount",
    "CatalogCoverage",
    "CatalogDocumentResult",
    "CatalogTool",
    "CachedChunkSummary",
    "CachedCorpusSynthesis",
    "CachedSummary",
    "CLAIM_EVIDENCE_LABELS",
    "ClaimClassificationCase",
    "ClaimClassificationCaseResult",
    "ClaimClassificationEvaluation",
    "ClaimClassifier",
    "ClaimEvidenceDecision",
    "ClaimEvidenceAssessment",
    "ClaimEvidenceLabel",
    "ClaimEvidenceSignals",
    "ClaimLabelMetrics",
    "ClaimVerification",
    "ClaimVerifier",
    "ClaimRelation",
    "ClaimReviewAction",
    "ClaimReviewProposal",
    "ClaimReviewRecord",
    "ClaimReviewStore",
    "ClaimReviewWorkspace",
    "CorpusCatalog",
    "CorpusDocument",
    "CorpusLoadResult",
    "CorpusQueryResult",
    "CorpusQueryService",
    "ConversationMessage",
    "ConversationResolution",
    "ConversationRole",
    "ConversationTurn",
    "ConservativeClaimVerifier",
    "DocumentSummaryBuildResult",
    "EVIDENCE_SPAN_VERSION",
    "EVIDENCE_SYNTHESIS_VERSION",
    "EvidenceBoundSynthesis",
    "EvidenceLedger",
    "EvidenceSpan",
    "EvidenceSynthesisStore",
    "EvidenceValidationIssue",
    "EvidenceVoice",
    "ExactCatalogArguments",
    "ExactCatalogResult",
    "ExactCatalogStatus",
    "GenerationTraceSettings",
    "GeneratedClaimCaseResult",
    "GeneratedClaimEvaluation",
    "GeneratedClaimEvaluationCase",
    "GeneratedClaimLabelMetrics",
    "GroundedAnswer",
    "GroundedAnswerer",
    "INDEX_PIPELINE_VERSION",
    "KnowledgeBuildResult",
    "LoadIssue",
    "NotebookRunOptions",
    "QueryTrace",
    "QueryTraceStore",
    "QueryTiming",
    "QueryTraceContext",
    "QueryRoute",
    "QueryRouteDecision",
    "QueryRuntime",
    "ReasonedAnswer",
    "ReasoningPlan",
    "ReasoningRound",
    "ReasoningStep",
    "ReasoningTrace",
    "RelevantPassage",
    "ResolvedClaimStatus",
    "RetrievedPassage",
    "RetrievalBenchmark",
    "RetrievalCase",
    "RetrievalCaseResult",
    "RetrievalEvaluation",
    "RetrievalProfiles",
    "RetrievalContribution",
    "RetrievalStrategyEvaluation",
    "RetrievalTraceSettings",
    "RouteMetrics",
    "RoutingCase",
    "RoutingCaseResult",
    "RoutingEvaluation",
    "RuntimeSettings",
    "SemanticCorpusSearch",
    "SemanticSearchResult",
    "ReciprocalRankFusionRetriever",
    "RetrieverArm",
    "SourceReference",
    "SynthesisClaimGroup",
    "SynthesisCoverage",
    "SummaryProgress",
    "SummaryStore",
    "TimingLog",
    "TimingRecord",
    "TrainingEvidence",
    "TraceFreshness",
    "TracedEvidence",
    "VoiceAnalysis",
    "VoiceSpan",
    "ReviewedTrainingExample",
    "analyze_voice",
    "apply_claim_review",
    "ask_conversational",
    "build_cached_document_summaries",
    "build_cached_knowledge",
    "build_evidence_bound_synthesis",
    "build_catalog_tools",
    "build_retrieval_profiles",
    "corpus_fingerprint",
    "classify_claim_evidence",
    "evaluate_claim_classifier",
    "evaluate_generated_claims",
    "evaluate_retrieval",
    "evaluate_retrieval_strategies",
    "evaluate_query_router",
    "execute_catalog_query",
    "extract_answer_claims",
    "extract_grounded_answer_claims",
    "export_reviewed_training_examples",
    "bm25_index_exists",
    "load_corpus",
    "load_corpus_config",
    "load_claim_classification_cases",
    "load_generated_claim_cases",
    "load_retrieval_cases",
    "load_query_runtime",
    "load_routing_cases",
    "load_or_build_bm25_retriever",
    "parse_author_aliases",
    "plan_reasoning",
    "route_query",
    "resolve_author_query",
    "resolve_conversation_query",
    "requires_multistep_reasoning",
    "review_trace_answer",
    "review_claim_proposal",
    "validate_evidence_spans",
    "validate_claim_classification_sources",
]
